apiVersion: v1
kind: Service
metadata:
  name: eks-php
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: eks-php
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-php
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: eks-php
  template:
    metadata:
      labels:
        app: eks-php
    spec:
      containers:
        - name: eks-php
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3306
              name: rdsport
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
